Fix missing header files in user tests
cms-dev/cms pull request #1172
Opened 2021-03-07 09:46 UTC by ranaldmiao

This PR primarily fixes the issue described in #1153 where header files cannot be found for user tests

This implementation re-uses the same header files as that for actual submissions. (Assumption: Task authors typically do not have different implementations for public and private header files.)

This PR also allows for graders for user tests to be downloaded. Previously, a HTTP 404 will be encountered when contestants select the option to download grader files from their user tests.

It seems that graders are not stored with the `.%l` suffix (Eg: `grader.%l`) but the original extension (Eg: `grader.cpp`) instead. Hence, this PR introduces an additional check for the original filename before declaring HTTP 404.

2021-03-18 18:05 UTC, andreyv requested changes
Thanks for the fixes!

The first change is related to `TaskType.get_auto_managers()`, which is supposed to return managers to be taken from the task. But you can see that currently there is no way for `get_auto_managers()` to account for a non-mandatory, arbitrarily named `.h` manager (even less so for additional `.o` managers). One could make it work now by returning `None` instead of `[]` from `Batch.get_auto_managers()`, but I don't think this is intended.

So I think that for now the proposed change is a sufficient short-term fix until a general solution is worked out.

The second change looks good. Managers are in general stored without `.%l` in the database, so it is fitting to do the same here.

2021-03-20 04:39 UTC, ranaldmiao commented
Thanks for the review, @andreyv 

Made the requested changes.

2021-03-26 20:00 UTC, andreyv approved these changes

2021-03-26 20:05 UTC, merged

2021-03-26 20:20 UTC, andreyv commented
Thanks, merged. Also added tests in 81fb9df98e90e710c87c9e5c44458577fc69f2a8.