Add a Telegram bot to send announcements and reply to questions.
cms-dev/cms pull request #1305
Opened 2024-12-08 18:07 UTC by veluca93

This bot is inspired by #1198 and by the ioi-germany implementation in https://github.com/ioi-germany/cms/blob/main/cms/service/TelegramBotService.py. It is implemented as a separate service, and does not modify the database.

The contest admin must configure a chat ID in which the bot will send questions as they arrive; they will be kept up to date as they are replied to or ignored. Announcements are also sent to this channel.

Members of the channel can reply to questions, either with pre-baked answers (with the inline keyboard) or by replying to the messages (and specifying `/answer`); they can also send announcements.

2024-12-08 18:34 UTC, Virv12 commented
A few notes:
- We should document why we are using yaml instead of json, it's not obvious.
- It would be useful to support multi-contest mode with `-c ALL`.
- Maybe we want to use `default_argument_parser`.

2024-12-08 19:37 UTC, veluca93 commented
> A few notes:
> 
> * We should document why we are using yaml instead of json, it's not obvious.

Added a comment

> * It would be useful to support multi-contest mode with `-c ALL`.

Done. In that case, announcements are not supported.

> * Maybe we want to use `default_argument_parser`.

Mostly done: this uses `contest_id_from_args` and `ask_for_contest`, but not `default_argument_parser` as that assumes it is passed a Service.

2024-12-09 10:59 UTC, wil93 requested changes
Let's also have the bot send the username of who asked the question, maybe we can replace the question ID (which doesn't sound very helpful, correct me if I'm wrong) with it.

2024-12-09 15:26 UTC, veluca93 commented
> Let's also have the bot send the username of who asked the question, maybe we can replace the question ID (which doesn't sound very helpful, correct me if I'm wrong) with it.

Done.

2024-12-13 09:51 UTC, wil93 approved these changes
I would really like to add some test coverage for this in the future. As agreed offline this is a contrib script so for the time being we can keep it as it is.

2024-12-13 09:53 UTC, merged

2025-07-30 13:19 UTC, prandla commented
> > * We should document why we are using yaml instead of json, it's not obvious.
> 
> Added a comment

@veluca93 the comment you added reads `# We use yaml instead of json or similar because`. Do you remember how you intended to finish that sentence? :)

2025-07-30 15:00 UTC, veluca93 commented
> > > * We should document why we are using yaml instead of json, it's not obvious.
> > 
> > 
> > Added a comment
> 
> @veluca93 the comment you added reads `# We use yaml instead of json or similar because`. Do you remember how you intended to finish that sentence? :)

Not at all! Although I imagine this might be related to JSON being bad with numbers.

Given the cms config file is now toml, maybe we could try using that?

2025-07-31 13:15 UTC, prandla commented
> Not at all! Although I imagine this might be related to JSON being bad with numbers.

"real" json is bad with numbers, but python doesn't convert integers to floats, instead it stores bigints in json directly, so it's perfectly fine as long as you encode in python and decode in python.

Seeing as this is supposed to be storage for internal data, not configuration, toml doesn't make sense to me. We don't even have a toml writer available, tomllib is for reading only.

This actually feels quite similar to what RWS is doing for its data storage, and RWS gets by fine with json.

Anyways i'm not going to refactor it just for the sake of it, i just hoped maybe you remembered what the justification was :)